### ISSUE TITLE
OpenSSLCrypto - Ubuntu 22.04

### ISSUE THREAD

**Issue by iThorgrim-Hub** [azerothcore/azerothcore-wotlk#11845]
### Current Behaviour

When I generate the server I get two errors: 
```bash
azerothcore-wotlk/src/server/worldserver/Main.cpp:217:5: error: use of undeclared identifier 'OpenSSLCrypto'
    OpenSSLCrypto::threadsSetup();
```

```bash
azerothcore-wotlk/src/server/worldserver/Main.cpp:219:62: error: use of undeclared identifier 'OpenSSLCrypto'
    std::shared_ptr<void> opensslHandle(nullptr, [](void*) { OpenSSLCrypto::threadsCleanup(); });
```

### Expected Blizzlike Behaviour

No error, i think ^^

### Steps to reproduce the problem

1. Download AzerothCore Source https://github.com/azerothcore/azerothcore-wotlk/commit/e5b0545759d792472323ab519fd27ce9dfb14409
2. Compile

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/e5b0545759d792472323ab519fd27ce9dfb14409

### Operating system

Ubuntu 22.04 Desktop

### Custom changes or Modules

No module or changes, fresh core

**Comment by Nyeriah** [comment]
Ubuntu 22 is shipped with OpenSSL 3.x which is not supported. To compile in Ubuntu must compile OpenSSL 1.1x manually

**Comment by iThorgrim-Hub** [comment]
I'll update the wiki for the next devs so I won't be lost...

**Comment by iThorgrim-Hub** [comment]
> ![image](https://user-images.githubusercontent.com/24550914/169849952-e8c82cde-f1b6-4a62-a1f9-139c9851d125.png)

Explaining to other developers how to install libdevssl 1.1.x would be a good thing ;)

**Comment by Kitzunu** [comment]
Feel free to. I dont know Linux
