### ISSUE TITLE
[MSVC] When building Azerothcore_wotlk emits some errors C2039、C2653、C2146、C4430 on MSVC

### ISSUE THREAD

**Issue by Apriltanq** [azerothcore/azerothcore-wotlk#10923]
### Current Behaviour

Hi, all
Azerothcore_wotlk fails to build on MSVC build main_20220223.01 due to errors C2039、C2653、C2146、C4430. Could you help look?

### Expected Blizzlike Behaviour

For Azerothcore_wotlk should be run pass on the windows.

### Steps to reproduce the problem

1. git clone https://github.com/azerothcore/azerothcore-wotlk F:\gitP\azerothcore\azerothcore-wotlk
2. cd F:\gitP\azerothcore\azerothcore-wotlk
3.  set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64
4. mkdir build_amd64
5. cd F:\gitP\azerothcore\azerothcore-wotlk\build_amd64
6. msbuild /m /p:Platform=x64 /p:Configuration=Release AzerothCore.sln /t:Rebuild 2>&1

### AC rev. hash/commit

None

### Operating system

Windows 10 x64

### Custom changes or Modules

Error Message：
58>F:\gitP\azerothcore\azerothcore-wotlk\build_amd64\googletest\googletest-src\googlemock\include\gmock/gmock-actions.h(819,36): error C2039: 'result_of': is not a member of 'std' [F:\gitP\azerothcore\azerothcore-wotlk\build_amd64\src\test\unit_tests.vcxproj]
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\bitset(22): message : see declaration of 'std' [F:\gitP\azerothcore\azerothcore-wotlk\build_amd64\src\test\unit_tests.vcxproj]
       F:\gitP\azerothcore\azerothcore-wotlk\build_amd64\googletest\googletest-src\googlemock\include\gmock/gmock-actions.h(825): message : see reference to class template instantiation 'testing::internal::InvokeMethodWithoutArgsAction<Class,MethodPtr>' being compiled [F:\gitP\azerothcore\azerothcore-wotlk\build_amd64\src\test\unit_tests.vcxproj]
    58>F:\gitP\azerothcore\azerothcore-wotlk\build_amd64\googletest\googletest-src\googlemock\include\gmock/gmock-actions.h(819,64): error C2653: 'result_of': is not a class or namespace name [F:\gitP\azerothcore\azerothcore-wotlk\build_amd64\src\test\unit_tests.vcxproj]
    58>F:\gitP\azerothcore\azerothcore-wotlk\build_amd64\googletest\googletest-src\googlemock\include\gmock/gmock-actions.h(819,66): error C2146: syntax error: missing ';' before identifier 'type' [F:\gitP\azerothcore\azerothcore-wotlk\build_amd64\src\test\unit_tests.vcxproj]
    58>F:\gitP\azerothcore\azerothcore-wotlk\build_amd64\googletest\googletest-src\googlemock\include\gmock/gmock-actions.h(819,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [F:\gitP\azerothcore\azerothcore-wotlk\build_amd64\src\test\unit_tests.vcxproj]

Build log:
[build.log](https://github.com/azerothcore/azerothcore-wotlk/files/8195430/build.log)

**Comment by Winfidonarleyan** [comment]
https://github.com/azerothcore/azerothcore-wotlk/runs/5442109854?check_suite_focus=true

**Comment by Apriltanq** [comment]
@Winfidonarleyan We are building the Azerothcore_wotlk with the latest unreleased compiler. These errors should be reported only with the unreleased compiler. They may occure in the next released compiler.

**Comment by Winfidonarleyan** [comment]
Now look at the errors carefully and tell me, what does our core have to do with it?

**Comment by acidmanifesto** [comment]
> @Winfidonarleyan We are building the Azerothcore_wotlk with the latest unreleased compiler. These errors should be reported only with the unreleased compiler. They may occure in the next released compiler.

We do not support preview or unsupported compilers.

**Comment by Apriltanq** [comment]
> 

OK, thanks for your replying
