### PR TITLE
fix a Mac build issue introduced by commit #17643

### PR DESCRIPTION
**Pull request by natrist**
## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

The Mac build fails with the following 2 error messages:
`src/common/Utilities/StringFormat.h:75:53: error: no type named 'locale' in namespace 'std'`
`src/common/Utilities/StringFormat.h:75:72: error: no member named 'locale' in namespace 'std'`

## Tests Performed:
- Built on macOS Sonoma 14.1.1 (23B81)

### CODE REVIEW

**Comment by dedmen** [comment]
I ran into same issue when building on Linux with clang 15.
And applied the same fix

**Review by Nyeriah — APPROVED** [review]
