### PR TITLE
fix(Core/Combat): use wand skill for auto attacks

### LINKED ISSUE #26557: [WAND]whatever the wanding skills you have it always do damage on the target
### Triage

Issue linked from CC: 
https://github.com/chromiecraft/chromiecraft/issues/9879

Triage Notes: 

- make a caster class
- .add any wand (like 5213 level 30 wand )
-  find a nearby mob that close to your level range
- hit it with a wand and observe

test vid: https://dl.dropboxusercontent.com/scl/fi/xa8pl5wjewfsee5uqei9h/Wow_2EiiXkeAIa.mp4?rlkey=0lk90vleik6ezenadf3a3g6pt&dl=0

twitch clip from 2024 : https://www.twitch.tv/videos/2312041685?t=3h29m8s

Original Post Below: 

---
### Current Behaviour

When you do a damage with a wand it always proc(do damage)

test vid: https://dl.dropboxusercontent.com/scl/fi/xa8pl5wjewfsee5uqei9h/Wow_2EiiXkeAIa.mp4?rlkey=0lk90vleik6ezenadf3a3g6pt&dl=0

### Expected Behaviour

It should miss at level 1 (not always) but have a higher chance of it missing 

### Official Sources (that prove or disprove) the issue being reported

this is a twitch clip from classic 2024 
https://www.twitch.tv/videos/2312041685?t=3h29m8s

### Steps to reproduce the problem

1. make a caster 
2. .add any wand (like 5213)
3. find a nearby mob that close to your level range 
4. hit it with a wand and observe

### Extra Notes

-

### Customizations

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/497cd60dcf9c5d6b0140ac91235f0923f8dbad64

### PR DESCRIPTION
**Pull request by moostigre**
## Changes Proposed:
Fix the wands not using ranged shoot hit calculation and producing hit chance disconnected from from skill level

This PR proposes changes to:
-  [X] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

### AI-assisted Pull Requests

> [!IMPORTANT]
> Using AI tools to prepare pull requests is allowed, but it must be disclosed and it must follow our AC guidelines for AI Agentic Engineering (link below).
>
> You are expected to fully understand the changes you submit and to be able to explain and justify them when maintainers ask.

- [ ] AI tools (e.g. Claude, ChatGPT, or similar) were used entirely or partially to prepare this pull request. If checked, specify which tools and models below.
   - Tools/models used:
- [ ] I have read and understood the [AC guidelines for AI Agentic Engineering](https://www.azerothcore.org/wiki/agentic-engineering)

## Issues Addressed:

- Closes #26557 

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by sudlud** [comment]
`Spell::prepareDataForTriggerSystem` still has the same wand check inlined, and that's the copy that actually runs for wand shots (`createProcFlags` only gets called from the split damage paths, always with `BASE_ATTACK`). can we use `IsWandAutoAttack()` there too?
https://github.com/azerothcore/azerothcore-wotlk/blob/397e662d61ae757604438a1fa6ef8ee1b7822e4a/src/server/game/Spells/Spell.cpp#L2281-L2283

can you add the hit/miss numbers you measured to the description? this shifts wand accuracy for every caster on a realm: at Wands skill 1 the miss chance clamps to the 60% cap in `MeleeSpellMissChance`, and at capped skill against a level 83 target it goes from 17% to 8%. worth confirming the skill still climbs while wanding, otherwise a low skill character stays at the cap.

where did you get the fix from? vmangos merged the same change in vmangos/core#3439 and mentions CMaNGOS Classic already doing it, so if you started from either of those the SOURCE section and the cherry-pick author tag should say so. if you worked it out yourself, linking them as supporting evidence would still help.

heads up for whoever tests this: the repro in #26557 (level 1 against a same level mob) looks about the same either way, 4% to 5.4% miss. the change only shows up at bigger skill gaps.

one for the description too: `m_modSpellHitChance` is only read in `MagicSpellHitResult`, so Misery, Shadow Focus and Elemental Precision stop affecting wands after this. gear hit rating still does, via `CR_HIT_RANGED`.

**Comment by moostigre** [comment]
The fix was made 100% by hand I didn't even think about checking what other cores did, I knew it was considered as physical range hit, yet doing magical damage so I looked upon adding it to what calculates for a throw weapon

I tested it at lvl 1, you get misses but the skill still levels up when you hit, as it should

**Comment by sudlud** [comment]
can we use `IsWandAutoAttack()` in `prepareDataForTriggerSystem` too? that's the copy that runs for wand shots, `createProcFlags` only fires on split damage.

can you add to the description that spell hit no longer applies to wands? `m_modSpellHitChance` is only read in `MagicSpellHitResult`, so Misery, Shadow Focus and Elemental Precision stop affecting wand shots, and hit comes from `CR_HIT_RANGED` instead of `CR_HIT_SPELL`. plus the numbers you measured.

side question: wands still crit off spell crit, `SpellDoneCritChance` switches on `DmgClass` and Shoot is `SPELL_DAMAGE_CLASS_MAGIC`. leave hit and crit split for now, or cover both here? wdyt

marking waiting to be tested. the repro in #26557 barely moves either way (4% to 5.4% miss at level 1), so what I'd rather see counted:

- level 80 with Wands still at 1 vs a level 80 mob: should sit at the 60% miss cap
- same character once Wands reaches 400, vs a level 83 target: ~8% miss, down from 17% today
- the skill still climbs while stuck at the cap, misses included
- +spell hit gear no longer moves the hit rate
- hunter Auto Shot and Throw unchanged

**Comment by moostigre** [comment]
good question for the spell crit, i remember the wanding is completely weird in this game but i wouldn't touch the crit in this PR and i would address it later once an answer to those mysteries can be found

ITEM_MOD_HIT_RATING increases melee, ranged and spell ratings together so spell hit gear shouldn't improve hit rating but hit rating gear should

i will modify the cleanup for IsWandAutoAttack()

**Comment by sudlud** [comment]
one more on the description: does this fully close #26557? the skill matters now, but the repro in the issue (level 1 vs a same level mob) barely moves either way. if it doesn't, please make it `Progresses #26557` so merging doesn't auto close it.

**Comment by moostigre** [comment]
it should close it as you wouldn't have 100% hit, I think the OP reported in that way "find a nearby mob that close to your level range" not sure he is talking about lvl 1 vs lvl 1 but more like "i am level 2 i am wanding a lvl 3 and not missing having low 20 wand skill"

**Comment by sudlud** [comment]
merged master in for you, the conflict was #27627 moving `SpellHitResult` over to `WorldObject`. `prepareDataForTriggerSystem` looks good now.

cppcheck has been failing since fca3458, it can't parse the two new test files:

```
src/test/server/game/Combat/WandCombatE2ETest.cpp:107:1: error: syntax error [syntaxError]
src/test/server/game/Combat/WandCombatTest.cpp:26:1: error: syntax error [syntaxError]
```

2ae07d7 and 397e662 were green, so it came in with the tests. can you repro and fix it? my guess is the `const_cast<std::vector<ItemTemplate*>*>` in `WandCombatTestFixture.h`, but I couldn't pin it locally.

```
cppcheck --force --inline-suppr --suppressions-list=./.suppress.cppcheck src/
```

the ctest filter in `src/test/CMakeLists.txt` doesn't do anything here, CI runs `build/src/test/unit_tests` straight (`.github/actions/linux-build/action.yml:218`) and never calls ctest. so all seven `ExpectMissRate` tests run in every build job, 20k full casts each. biggest loop anywhere else in `src/test/` is 100 iterations, can we cut the samples way down?

`Fire()` also runs `CheckCast` twice per shot, once directly and once inside `prepare()`.

can we remove `src/test/server/game/Combat/docs/wand-combat-tests.md`? the numbers belong in the PR description, and the file has the PR number in its title plus a dated run log.

description still needs those numbers, plus a note that spell hit no longer applies to wands (`m_modSpellHitChance` is only read in `MagicSpellHitResult`), and the AI tools box ticked if you used any for the test package.

**Comment by moostigre** [comment]
fixed the docs and i reduced the test loops, fixed the errored enum
