### PR TITLE
fix(CMake): AzerothCore now compiles on Ubuntu 26.04

### PR DESCRIPTION
**Pull request by Chinoske**
## Changes Proposed:

Ubuntu 26.04 cannot compile AzerothCore with clang. Clang builds against the newest GCC toolchain installed on the box, and on that release it picks GCC 16, whose libstdc++ headers it cannot parse. The build dies before reaching any of our code:

```
/usr/lib/gcc/x86_64-linux-gnu/16/../../../../include/c++/16/shared_mutex:528:33: fatal error: no member named '__to_timeout_timespec' in namespace 'std::chrono'
```

```
/usr/lib/gcc/x86_64-linux-gnu/16/../../../../include/c++/16/numeric:302:21: fatal error: no template named '__is_any_random_access_iter'; did you mean '__is_random_access_iter'?
```

GCC 16 ends up on the box even though 26.04 defaults to GCC 15, because Ubuntu ships a single `libstdc++6` built against 16 for both, so installing clang pulls the whole GCC 16 toolchain in. Thanks to @CheckYourFax for working that part out.

This adds a fallback to `src/cmake/compiler/clang/settings.cmake`: probe whether clang can use its default toolchain, and if it cannot, try each installed GCC newest first and pass `--gcc-install-dir` for the first one that works. A box where the default already works never sees the flag, and the whole block can go once clang can consume the libstdc++ shipped next to it.

That file is where clang-specific handling already lives, and it already carries this exact shape: a `check_cxx_source_compiles` probe for a clang bug in the standard library, with a note saying it can be removed once the minimum clang version is raised. The flag is applied through `target_compile_options` on `acore-compile-option-interface`, the same way the sanitiser blocks do it, so it does not clobber flags passed in from outside.

The probe instantiates rather than only including. Both failures live in templates the compiler does not look at until something uses them, so a bare `#include` of those two headers compiles cleanly even on a box where the real build dies. That is worth knowing before testing this by hand.

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

### AI-assisted Pull Requests

> [!IMPORTANT]
> Using AI tools to prepare pull requests is allowed, but it must be disclosed and it must follow our AC guidelines for AI Agentic Engineering (link below).
>
> You are expected to fully understand the changes you submit and to be able to explain and justify them when maintainers ask.

- [x] AI tools (e.g. Claude, ChatGPT, or similar) were used entirely or partially to prepare this pull request. If checked, specify which tools and models below.
   - Tools/models used: Claude Code (Opus 5)
- [x] I have read and understood the [AC guidelines for AI Agentic Engineering](https://www.azerothcore.org/wiki/agentic-engineering)

## Issues Addressed:
- None

## SOURCE:
The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

Code inspection: `libstdc++-16-dev` is already installed by #26940 and the failing runs confirm it (`Setting up libstdc++-16-dev:amd64 (16-20260322-1ubuntu1)`), so this is not the missing package that fixed. Dropping the package again would not help either: clang still selects the GCC 16 toolchain and then fails to link, which is what #26940 was addressing. The toolchain has to be named explicitly.

The reason master looks unaffected is ccache. The ubuntu-26.04 legs of `Dashboard CI`, `pch-build` and `nopch-build` all finish there in under 5 minutes against roughly 45 for a real build, so nothing is compiled and the headers are never parsed. Only a pull request touching core files rebuilds enough to hit it, which is why #26735 and #26820 are red on a job that has nothing to do with their changes.

An earlier revision of this PR did the same thing in `apps/compiler/includes/functions.sh`. That was the wrong place twice over: it only covered people building through the dashboard, and it reimplemented what `check_cxx_source_compiles` already does.

## Tests Performed:
This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [x] This pull request requires further testing and may have edge cases to be tested.

The selection logic was exercised on its own with `cmake -P` against a tree of fake toolchain directories: it walks them newest first, skips the ones the probe rejects, applies the flag for the first that passes and stops there.

The clang path itself needs a 26.04 box, so this pull request's own CI run is the real test. Note that a green run there does not prove much on its own, since a warm ccache can finish that leg in a handful of minutes without compiling anything. What to look for is `Clang: cannot use the default GCC toolchain, falling back to ...` in the configure output.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [x] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

On an Ubuntu 26.04 box with the stock clang:

1. Before this change, configuring and building fails in `<shared_mutex>` and `<numeric>` as above.
2. With it, cmake prints either nothing, if clang was already fine, or `Clang: cannot use the default GCC toolchain, falling back to /usr/lib/gcc/x86_64-linux-gnu/15`, and the build proceeds.
3. On 24.04, and anywhere else the default pairing works, the probe passes and nothing is added.

If you want to check by hand whether your box is affected, the include-only test is not enough. This is one that reaches the failing templates:

```
printf '#include <numeric>\n#include <shared_mutex>\n#include <vector>\n#include <chrono>\nint main(){std::vector<int> v{1,2,3};std::shared_timed_mutex m;(void)std::reduce(v.begin(),v.end());(void)m.try_lock_for(std::chrono::seconds(1));}\n' | clang++ -x c++ -std=c++20 -fsyntax-only -
```

## Known Issues and TODO List:

- None

## How to Test AzerothCore PRs

When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

File: apps/compiler/includes/functions.sh [hunk 1]
```diff
@@ -58,6 +58,33 @@ function comp_ccacheShowStats() {
     ccache -s
 }
 
+# clang builds against the newest GCC toolchain installed on the box. When that
+# toolchain is newer than clang understands, compilation dies inside the standard
+# headers before reaching any of our code: clang 21 with GCC 16 on Ubuntu 26.04
+# fails in <shared_mutex> and <numeric>. Fall back to the newest GCC that clang can
+# actually parse. Does nothing where the default already works.
+function comp_selectGccToolchain() {
+  [[ "$($CCOMPILERCXX --version 2>/dev/null | head -1)" == *clang* ]] || return 0
```
[the remark this answers is not in the document]
Comment (Chinoske) [reply apps/compiler/includes/functions.sh]: good catch, thanks. dropped the CFLAGS line instead of guarding it: the C compiler never sees libstdc++, so it does not need the flag at all.

**Comment by CheckYourFax** [comment]
Clang 21, the default clang toolchain depends on libstdc++6.

Now look at https://packages.ubuntu.com/resolute/libstdc++6

This is built against GCC 16, when the default GCC version is 15.2. For some reason the package maintainers decided to make libstdc++6 be built against GCC 16 for both 15 and 16. This is the reason apt pulls in the entire GCC 16 toolchain when you install clang.

Ubuntu advertised 26.04 as using gcc 15.2 as default toolchain, but keep gcc-16 as option. That is nice of them of course. But now they just decided to have one version of libstdc++ for both gcc-16 and gcc-15 and that's why gcc-16 is pulled in.

To me it seems like some true packaging laziness to not have a version of libstdc++6 for 15.2 so that people can avoid pulling in the entire gcc-16 toolchain.


**Footnote:** I do not have issues parsing libstdc++-16-dev with Clang 21.

**Comment by Chinoske** [comment]
thanks, that explains the piece I could not work out: why the GCC 16 toolchain ends up on the box at all when 15.2 is meant to be the default. one libstdc++6 built against 16 for both is exactly it.

on the footnote, mine is the github ubuntu-26.04 runner with the stock clang 21 and `libstdc++-16-dev 16-20260322-1ubuntu1`, building at C++20. it dies in `<numeric>`, reached from `ObjectMgr.cpp`, and in `<shared_mutex>`:

```
/usr/lib/gcc/x86_64-linux-gnu/16/../../../../include/c++/16/numeric:302:21: fatal error: no template named '__is_any_random_access_iter'; did you mean '__is_random_access_iter'?
```

full logs in [job 92198476550](https://github.com/azerothcore/azerothcore-wotlk/actions/runs/30972100383/job/92198476550) and [job 92198492917](https://github.com/azerothcore/azerothcore-wotlk/actions/runs/30972106279/job/92198492917). that package is a dated snapshot, so a different one on your side coping fine would not surprise me at all. if you feel like checking, this is the whole repro:

```
echo -e '#include <shared_mutex>\n#include <numeric>' | clang++ -x c++ -std=c++20 -fsyntax-only -
```

would be good to know either way, since it tells us whether this is the snapshot or something about the runner.

worth saying the change is a probe rather than a switch: if clang compiles those two headers, nothing is appended and your setup never sees the flag. it only does anything where the default pairing is already broken, and it stops doing anything the day it is not.

**Comment by CheckYourFax** [comment]
```
root@ubuntu:~# echo -e '#include <shared_mutex>\n#include <numeric>' | clang++ -x c++ -std=c++20 -fsyntax-only
```

(output empty, no error)

to verify clang is using gcc 16 libs, here's a printf:
```
root@ubuntu:~# printf '#include <numeric>\n#include <shared_mutex>\n' | clang++ -x c++ -std=c++20 -fsyntax-only -v -
Ubuntu clang version 21.1.8 (6ubuntu1)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-21/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/15
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/16
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/16
Candidate multilib: .;@m64
Selected multilib: .;@m64
 (in-process)
 "/usr/lib/llvm-21/bin/clang" -cc1 -triple x86_64-pc-linux-gnu -fsyntax-only -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name - -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fdebug-compilation-dir=/root -v -fcoverage-compilation-dir=/root -resource-dir /usr/lib/llvm-21/lib/clang/21 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/16/../../../../include/c++/16 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/16/../../../../include/x86_64-linux-gnu/c++/16 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/16/../../../../include/c++/16/backward -internal-isystem /usr/lib/llvm-21/lib/clang/21/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/16/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=c++20 -fdeprecated-macro -ferror-limit 19 -fmessage-length=242 -fgnuc-version=4.2.1 -fno-implicit-modules -fskip-odr-check-in-gmf -fcxx-exceptions -fexceptions -fcolor-diagnostics -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -x c++ -
clang -cc1 version 21.1.8 based upon LLVM 21.1.8 default target x86_64-pc-linux-gnu
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/16/../../../../x86_64-linux-gnu/include"
ignoring nonexistent directory "/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-linux-gnu/16/../../../../include/c++/16
 /usr/lib/gcc/x86_64-linux-gnu/16/../../../../include/x86_64-linux-gnu/c++/16
 /usr/lib/gcc/x86_64-linux-gnu/16/../../../../include/c++/16/backward
 /usr/lib/llvm-21/lib/clang/21/include
 /usr/local/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
root@ubuntu:~# 
```

**Comment by CheckYourFax** [comment]
I am gathering full logs from a fresh Incus Ubuntu 26.04 container all the way from apt update && upgrade to compiling AzerothCore. I'll try to compare and find out what is wrong with the CI.

**Comment by CheckYourFax** [comment]
#26999

Gotta get this merged to fix ./acore.sh install-deps on Ubuntu 26.04 when in a root shell.

I think more testing before merging stuff is something to improve on here, especially related to build env and CI.

**Comment by Chinoske** [comment]
reworked this, it now touches one file instead of the dashboard scripts.

the fallback lives in `src/cmake/compiler/clang/settings.cmake`, which is where clang specific handling already goes and which already carries this exact shape: a `check_cxx_source_compiles` probe for a clang bug in the standard library, with a note saying it can be dropped once the minimum clang version is raised. the flag is applied through `target_compile_options` on `acore-compile-option-interface` like the sanitiser blocks do, so it does not clobber anything passed in from outside.

doing it there also covers more ground than the previous version did. the bash one only helped people building through `./acore.sh`; this one goes through cmake, so it works for a plain cmake build, an IDE, and the `linux-build` action too.

one thing worth knowing before anyone tests by hand: a bare `#include <shared_mutex>` and `<numeric>` compiles fine even on a box where the real build dies, because both failures are inside templates the compiler never looks at until something uses them. that is why the first revision of this PR did nothing at all. this is the version that reproduces it:

```
printf '#include <numeric>\n#include <shared_mutex>\n#include <vector>\n#include <chrono>\nint main(){std::vector<int> v{1,2,3};std::shared_timed_mutex m;(void)std::reduce(v.begin(),v.end());(void)m.try_lock_for(std::chrono::seconds(1));}\n' | clang++ -x c++ -std=c++20 -fsyntax-only -
```

ready for a look whenever someone has a moment. worth noting a green run here does not prove much on its own, a warm ccache finishes that leg in a few minutes without compiling anything. the thing to look for is `Clang: cannot use the default GCC toolchain, falling back to ...` in the configure output.

**Comment by Chinoske** [comment]
closing this: the premise does not hold. @CheckYourFax was right.

went and tested it properly on a real Ubuntu 26.04 rather than reasoning from CI logs, with the same versions the runner has:

```
Ubuntu clang version 21.1.8 (6ubuntu1)
g++ (Ubuntu 15.2.0-16ubuntu1) 15.2.0
libstdc++-16-dev  16-20260322-1ubuntu1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/16
```

same clang, same libstdc++ package, clang picking GCC 16 exactly like the runner does. both probes compile clean, including the one that instantiates `std::reduce` and `shared_timed_mutex::try_lock_for`, which is what reaches the templates the runner dies in. so clang 21 parses libstdc++ 16 fine and there is nothing here for a toolchain flag to fix.

what the runner error actually says is more specific than I read it:

```
numeric:302:21: fatal error: no template named '__is_any_random_access_iter'; did you mean '__is_random_access_iter'?
```

`__is_any_random_access_iter` is declared in `bits/stl_iterator_base_funcs.h`, same package, and on a clean box `<numeric>` sees it. For it to be missing while `<numeric>` still uses it, the compile has to be seeing a mixed set of headers: the new `numeric` against older iterator traits.

which points at the build state rather than the toolchain. from the failing job:

```
Cache restored from key: ccache:ubuntu-26.04:clang-21_clang++-21:26735/merge-30966572568
CCACHE_SLOPPINESS = include_file_mtime, pch_defines, time_macros
```

the cache key covers the OS and the compiler, but nothing about the C++ standard library. #26940 installed `libstdc++-16-dev` on 3 Aug, which changed the system headers without changing the key, so runs after it restore caches, and precompiled headers, built before those headers existed. with `pch_defines` and `include_file_mtime` relaxed, a PCH snapshotted against the old header set gets reused against the new `<numeric>`. that is the mix the error describes, and it fits the rest: master stays green because it is a full cache hit and compiles nothing, and only PRs touching core files rebuild enough to hit it.

I have not proven that last part, so treating it as the lead rather than the answer. two ways to check, both cheap:

- clear the ccache for the ubuntu-26.04 legs once and re-run. if they go green, the caches carried over the package change.
- or add the stdlib version to the cache key so this cannot happen again, e.g. folding `dpkg-query -W -f='${Version}' libstdc++-*-dev` into the key next to the compiler id, in `dashboard-ci.yml` and in `.github/actions/linux-build`.

happy to open that second one if it sounds right, but I would rather someone who owns the CI says which way they want it than guess again.

sorry for the noise on this one. lesson taken: I should have run it on a 26.04 box before opening anything, which is exactly what @sudlud asked for elsewhere today.
