### ISSUE TITLE
[MSVC] Compile error C2440: 'return': cannot convert from 'const boost::filesystem::path::string_type' to 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'

### ISSUE THREAD

**Issue by moyoumiu** [azerothcore/azerothcore-wotlk#17250]
### Current Behaviour

Failed to build with error C2440:

```log
Config.cpp
src\test\common\Configuration\Config.cpp(39,5): error C2440: 'return': cannot convert from 'const boost::filesystem::path::string_type' to 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'
src\test\common\Configuration\Config.cpp(39,5): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
```

### Expected Blizzlike Behaviour

No error.

### Source

[src/test/common/Configuration/Config.cpp](https://github.com/azerothcore/azerothcore-wotlk/blob/e2eef06317cbdabeb377476a6fae695f00d4e466/src/test/common/Configuration/Config.cpp)

### Steps to reproduce the problem

```cmd
mkdir S:\az\build_amd64
cd /d S:\az\build_amd64
set BOOST_ROOT=S:\boost-binaries\boost_1_83_0-msvc-14.3-64
set MYSQL_ROOT=S:\mysql_5_7_35\mysql-5.7.35-winx64
set OPENSSL_ROOT=S:\OpenSSL\64
cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22621.0 -DCMAKE_BUILD_TYPE=Release -DTOOLS=ON -DBUILD_TESTING=ON .. 2>&1

set _CL_=/D_HAS_DEPRECATED_RESULT_OF=1 /D_SILENCE_CXX17_RESULT_OF_DEPRECATION_WARNING
msbuild /m /p:Platform=x64 /p:Configuration=Release AzerothCore.sln /t:Rebuild 2>&1
```

### Extra Notes

Visual Studio 2022 17.7.3

### AC rev. hash/commit

e2eef06

### Operating system

Microsoft Windows [Version 10.0.22621.2283]

**Comment by Kitzunu** [comment]
I belive it is an issue with Boost 1.83

Downgrade to 1.81 and it should work.

I will start work on boost 1.83 support.

**Comment by Kitzunu** [comment]
```
========== Build: 11 succeeded, 0 failed, 8 up-to-date, 1 skipped ==========
```
Boost 1.83
MSVC Version 17.7.4

Cannot reproduce.

**Comment by moyoumiu** [comment]
> ```
> ========== Build: 11 succeeded, 0 failed, 8 up-to-date, 1 skipped ==========
> ```
> 
> Boost 1.83 MSVC Version 17.7.4
> 
> Cannot reproduce.

Here is the build files and cl.exe parameter file could reproduce.

#### Command
```
cl @cl.rsp
```
#### Source Files
[azerothcorewotlk-clrepro.zip](https://github.com/azerothcore/azerothcore-wotlk/files/12658716/azerothcorewotlk-clrepro.zip)

**Comment by moyoumiu** [comment]
> > ```
> > ========== Build: 11 succeeded, 0 failed, 8 up-to-date, 1 skipped ==========
> > ```
> > 
> > 
> > Boost 1.83 MSVC Version 17.7.4
> > Cannot reproduce.
> 
> @Kitzunu Here are the build files and cl.exe parameter file could reproduce.
> 
> #### Source Files
> [azerothcorewotlk-clrepro.zip](https://github.com/azerothcore/azerothcore-wotlk/files/12658716/azerothcorewotlk-clrepro.zip)
> 
> #### Command
> ```
> cl @cl.rsp
> ```

@Kitzunu The compressed package contains the extracted source
