### PR TITLE
fix(Core/Eluna): fix compiler warning concerning Eluna

### PR DESCRIPTION
**Pull request by Stoabrogga**
##### CHANGES PROPOSED:
Fix the following compiler warning by reordering the parameters:
```
src/server/game/Entities/Object/Object.cpp:967:65: fatal error: field 'LastUsedScriptID' will be initialized after field 'elunaEvents' [-Wreorder]
WorldObject::WorldObject(bool isWorldObject) : WorldLocation(), LastUsedScriptID(0),
```
This is necessary as preparation for including Eluna into the Travis run (see https://github.com/azerothcore/mod-eluna-lua-engine/pull/11 and #1663)

###### ISSUES ADDRESSED:
none

##### TESTS PERFORMED:
tested build on Ubuntu 16.04 incl. Eluna with warnings enabled, clang 7

##### HOW TO TEST THE CHANGES:
other than the build no testing is necessary

##### KNOWN ISSUES AND TODO LIST:
none

##### Target branch(es):
Master

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
nice
