### PR TITLE
Cmake: Use inherited dependencies

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
##### CHANGES PROPOSED:
**1. General**
- Added `INTERFACE` library for to only use includes directives this library **(see Examples)**
- If you connect the `shared` library, it will include several more libraries
- - ace
- - mysql
- - g3dlib
- - Detour
- - sfmt
- - utf8cpp
- - openssl
- - threads
- - jemalloc
- Added new macros `AutoCollect` which has 2 functions **(see Examples)**
- - CollectSourceFiles 
- - CollectIncludeDirectories 

**2. Misc**
- Move lib `collision` to `shared`
- Added `GroupSources` in all remaining library

#### Added `cotire` module for precompiled header handling https://github.com/sakra/cotire
- Required for handling flags inherited by linked projects
  correctly in the corresponding precompiled header.
- Reduces the maintenance effort for precompiled headers

#### Examples
- For example `game-interface`can be used in library `scripts`
```cmake
target_link_libraries(scripts
  PRIVATE
    scripts-interface
    game-interface)
```
- For example in library `game` can use macros `CollectSourceFiles` in order not to list them manually

**Before**
```cmake
file(GLOB_RECURSE sources_Accounts Accounts/*.cpp Accounts/*.h)
file(GLOB_RECURSE sources_Achievements Achievements/*.cpp Achievements/*.h)
file(GLOB_RECURSE sources_Addons Addons/*.cpp Addons/*.h)
file(GLOB_RECURSE sources_AI AI/*.cpp AI/*.h)
...
```

**After**
```cmake
CollectSourceFiles(
  ${CMAKE_CURRENT_SOURCE_DIR}
  PUBLIC_INCLUDES
  # Exclude
  ${CMAKE_CURRENT_SOURCE_DIR}/PrecompiledHeaders)
```
**PR based TC commits**
- https://github.com/TrinityCore/TrinityCore/commit/1a572d242593124f986d3ed08710b96a142a6763
- https://github.com/TrinityCore/TrinityCore/commit/2413a82b9343178b613bc6309125eecec8aa9123
- https://github.com/TrinityCore/TrinityCore/commit/abda7a910a760687f9c1b9e0893314e04982c0f1
- https://github.com/TrinityCore/TrinityCore/commit/469f2d3ade168de0b5be18112008c337067a8e03
- https://github.com/TrinityCore/TrinityCore/commit/96bc31924a5a418d37bd961ef2880f9072126348
- https://github.com/TrinityCore/TrinityCore/commit/03d249f0631c3561070ebbdd7301115507c68876
- https://github.com/TrinityCore/TrinityCore/commit/92f96fc10e70b2d62cce832837477d958e2afbe3

##### TESTS PERFORMED:
- [x] Build in VS 16 2019 (Win)

##### HOW TO TEST THE CHANGES:
- [x] Build in Travis no PCH
- [x] Build in Travis witch PCH

##### Target branch(es): Master

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
why

**Comment by Winfidonarleyan** [comment]
@BarbzYHOOL, what do you mean?

**Comment by Viste** [comment]
Because!

**Comment by Viste** [comment]
Cmake fails on linux:
https://paste2.org/DP2VW85h
https://paste2.org/k9H0mIVx -- output
https://paste2.org/9eaU3JVO --error

**Comment by Stoabrogga** [comment]
@Winfidonarleyan 
Could you please elaborate on these changes? I read your comment, but I don't really understand what this is all about.

**Comment by BarbzYHOOL** [comment]
> @Winfidonarleyan
> Could you please elaborate on these changes? I read your comment, but I don't really understand what this is all about.

Exact, it's good to port stuff from Tc all the time but there must be a reason other than "it's on TC so we port it". Else we will end up with all the problems TC has, no?

**Comment by Winfidonarleyan** [comment]
I'll try to answer when I'm done.

**Comment by Viste** [comment]
First of all Cmake and build be more faster!
Then its allow to remove CMake wrrnings(must do it!)
and This allow dynamic load of included dirs and files, so the shit like:
```
file(GLOB_RECURSE sources_Accounts Accounts/*.cpp Accounts/*.h)
file(GLOB_RECURSE sources_Achievements Achievements/*.cpp Achievements/*.h)
file(GLOB_RECURSE sources_Addons Addons/*.cpp Addons/*.h)
file(GLOB_RECURSE sources_AI AI/*.cpp AI/*.h)
file(GLOB_RECURSE sources_AuctionHouse AuctionHouse/*.cpp AuctionHouse/*.h)
file(GLOB_RECURSE sources_Battlefield Battlefield/*.cpp Battlefield/*.h)
file(GLOB_RECURSE sources_Battlegrounds Battlegrounds/*.cpp Battlegrounds/*.h)
file(GLOB_RECURSE sources_Calendar Calendar/*.cpp Calendar/*.h)
file(GLOB_RECURSE sources_Chat Chat/*.cpp Chat/*.h)
file(GLOB_RECURSE sources_Combat Combat/*.cpp Combat/*.h)
file(GLOB_RECURSE sources_Conditions Conditions/*.cpp Conditions/*.h)
file(GLOB_RECURSE sources_DataStores DataStores/*.cpp DataStores/*.h)```
will be deleted from cmake list in game folder

**Comment by Viste** [comment]
and please stop hitting trinity for trying to make their code clean and correct from the viewpoint of C/C++ programming standards

**Comment by BarbzYHOOL** [comment]
There is theory and there is practice. In theory, it's awesome. In practice, it can lead to big issues (I'm not specifically worried about this particular PR though, but in general)


Anyway thank you for that bit of explanation

File: apps/ci/ci-install.sh [hunk 1]
```diff
@@ -26,8 +26,8 @@ CTYPE=Release
 CSCRIPTS=$1
 CSERVERS=ON
 CTOOLS=ON
-CSCRIPTPCH=OFF
-CCOREPCH=OFF
+CSCRIPTPCH=ON
+CCOREPCH=ON
```
Comment (BarbzYHOOL) [inline apps/ci/ci-install.sh]: No, why did you change that??

It needs to be set to OFF because PCH (precompiled headers) are optional. Travis must not compile them with PCH on because else it is possible that modules/scripts are missing headers and then compilation failed. This is something me, rochet and most notably @Stoabrogga had to deal with. Unless I'm making a mistake, of course.

**Comment by Viste** [comment]
Builds fine on Mint 18.3 and Debian 9 https://paste2.org/dEI0Abg7
travis is idiot

**Comment by FrancescoBorzi** [comment]
I've restarted the Travis build

**Comment by BarbzYHOOL** [comment]
Don't merge before the PCH thing is addressed

**Comment by Viste** [comment]
PCH is OK trevis just an idiot

**Comment by FrancescoBorzi** [comment]
> PCH is OK trevis just an idiot

that is possible, however we cannot merge it until it's fixed otherwise master will always fail and we won't know when it's actually broken or not

**Comment by Winfidonarleyan** [comment]
Don't merge,

File: apps/ci/ci-install.sh (hunk 1 above)
Comment (Winfidonarleyan) [reply apps/ci/ci-install.sh]: This commit only test witch pch ...

**Comment by Viste** [comment]
do what you want, your core is — decision

File: apps/ci/ci-install.sh (hunk 1 above)
Comment (BarbzYHOOL) [reply apps/ci/ci-install.sh]: ok so it was only temporary?

**Comment by Winfidonarleyan** [comment]
@Viste need retest this :D

**Comment by brussens** [comment]
Tested Win10x64.
Good works.

**Comment by Winfidonarleyan** [comment]
@brussens thanks for test

**Comment by Viste** [comment]
linux still ok build finish in 20 minuts on old quad mobile AMD A10
https://paste2.org/9IveWOya
On 1 core virtual cpu about 1h(befor 1,45-2h)

**Comment by FrancescoBorzi** [comment]
Tested on Docker too. Everything looks good on my side.

I already see a good, big benefit: when recompiling the same sourceusing the build cache, it is super-fast. Before it took some extra time to recompile the same thing, uselessly.

- Thanks a lot @Viste and @brussens for your feedback
- Thanks to the original author @Naios
- And, of course, big thanks to @Winfidonarleyan who imported this to AC!

**Comment by Winfidonarleyan** [comment]
Thanks for test, @FrancescoBorzi

**Comment by Nefertumm** [comment]
Awesome! Thanks @Winfidonarleyan

**Comment by BarbzYHOOL** [comment]
Thank you @Winfidonarleyan @Viste @FrancescoBorzi
