### PR TITLE
feat(Core/Config): rework config and delete ACE inherited

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
## Changes Proposed:
- Delete `ACE_Configuration` inherited
- Full switch to std lib
- Cherrypick `StringConvert` from TrinityCore
- Add CMake macro for copy default and modules configs
- Add new getters `GetOption<bool>` and etc
- Add info about all modules configs after generating sources
- Add a new folder for all configs `configs`
- Add a new folder for all module configs `configs/modules`
---
- New folder for default configs non Windows systems
image
- New folder for modules configs non Windows systems
image

## Issues Addressed:
- Part #3451
- Part #3815

## Tests Performed:
- Builds and in-game

## Target Branch(es):
- [x] Master

----
## Media
1. New folder `configs` in Windows
image
2. New folder `configs/modules` in Windows
image
3. Config list after CMake source generated
image
4. Testing in game
image

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan the build is failing

File: src/common/Configuration/Config.h [hunk 1]
```diff
@@ -17,40 +19,46 @@ class ConfigMgr
...
+    std::string const GetConfigPath();
+    std::vector<std::string> const& GetArguments() const;
+    std::vector<std::string> GetKeysByString(std::string const& name);
 
-    std::string GetStringDefault(std::string const& name, const std::string& def, bool logUnused = true);
-    bool GetBoolDefault(std::string const& name, bool def, bool logUnused = true);
-    int GetIntDefault(std::string const& name, int def, bool logUnused = true);
-    float GetFloatDefault(std::string const& name, float def, bool logUnused = true);
+    template<class T>
+    T GetOption(std::string const& name, T const& def, bool showLogs = true) const;
```
Comment (FrancescoBorzi) [inline src/common/Configuration/Config.h:36]: @Winfidonarleyan I like the approach using generic types (templates). However, I think we should also keep the old methods and mark them as deprecated so we won't break modules and can give the opportunity to migrate them without failures. EXAMPLE:

```cpp
// @deprecated DO NOT USE - use GetOption<float> instead.
float GetFloatDefault(std::string const& name, float def, bool logUnused = true)
{
    return GetOption<float>(name, def, logUnused);
}
```

Comment (Kitzunu) [reply src/common/Configuration/Config.h:36]: Or the owner of the modules update to the new standard.

Perhaps it could be kept for a transitional period, a couple of weeks. But after that imo we dont need duplicate code

Comment (FrancescoBorzi) [reply src/common/Configuration/Config.h:36]: yes it's definitely for a transitional period, but 2 weeks is not enough

**Comment by Viste** [comment]
image

**Comment by Mitradis** [comment]
jv5l3v9svse-1-kopiya

**Comment by Mitradis** [comment]
Tested on windows, work.

**Comment by Winfidonarleyan** [comment]
Done

**Comment by FrancescoBorzi** [comment]
@azerothcore/developers  @azerothcore/testers @pklloveyou @mpfans please have a look at this

**Comment by nicoaravena** [comment]
Using ubuntu 20.04 and g++, works fine, running without errors also no warnings while compiling.

**Comment by FrancescoBorzi** [comment]
@nicoaravena @Mitradis have you tried using the config? e.g. changing a value, then doing a `.reload conf` and check if the change is reflected

**Comment by nicoaravena** [comment]
imagen
Have this error with the command.

**Comment by FrancescoBorzi** [comment]
> imagen
> Have this error with the command.

Thanks @nicoaravena for your feedback. Summoning @Winfidonarleyan

**Comment by Winfidonarleyan** [comment]
@nicoaravena retry

**Comment by Mitradis** [comment]
Work

**Comment by nicoaravena** [comment]
@Winfidonarleyan now works good.

**Comment by mpfans** [comment]
update to https://github.com/azerothcore/azerothcore-wotlk/commit/b9e132a9416197a78d72e08780c4cead2d039219
and then Merge this PR,Compilation error
image

**Comment by Winfidonarleyan** [comment]
Re run cmake

**Comment by mpfans** [comment]
ubuntu 18.04  test failed....

image

**Comment by Winfidonarleyan** [comment]
What is your clang? Show full CMake clean log

**Comment by FrancescoBorzi** [comment]
@mpfans you probably have a compiler that is too old. It compiles fine on Ubuntu 18.04 using `clang 6` and `gcc 8.4` and higher versions. Older versions are not supported
