### PR TITLE
Cmake: Add new method addings Eluna files in game lib

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
##### CHANGES PROPOSED:
-  Add new method addings files ElunaLuaEngine in game library

##### TESTS PERFORMED:
- [x] Build in VS 16 2019

##### HOW TO TEST THE CHANGES:
- See PR https://github.com/azerothcore/mod-eluna-lua-engine/pull/12

##### KNOWN ISSUES AND TODO LIST:
- [x] Build in Linux (Travis)
- [ ] Test in game

##### Target branch(es): Master

### CODE REVIEW

**Comment by Stoabrogga** [comment]
Tested build on Ubuntu 16.04 with clang 7 incl. the eluna module and everything seems to be ok. There are a few minor warnings which need to be fixed before the Travis run incl. eluna will succeed. I opened PRs for this:
https://github.com/ElunaLuaEngine/Eluna/pull/288
#1671 

Cannot test this in-game as I'm not using eluna.

**Comment by Winfidonarleyan** [comment]
So, maybe merge?

**Comment by Deku** [comment]
I'm not an Eluna user, so I can't review this. But if others say it's ok and there's no compilation error, then I guess it's ok? In this case an integration test including the module would be great :D

**Comment by gtao725** [comment]
I just compiled with Eluna using this PR, worked flawlessly. Can merge I think.

**Comment by Winfidonarleyan** [comment]
@gtao725 Thanks for test

**Comment by BarbzYHOOL** [comment]
@gtao725 are you on our discord?
