### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by ide1234000** [azerothcore/azerothcore-wotlk#2293]
##### SMALL DESCRIPTION:

I got an error when compiling the most recent source code with Ubuntu and the compilation failed.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Compiled successfully

##### CURRENT BEHAVIOUR:

![Screenshot from 2019-09-18 01-12-00](https://user-images.githubusercontent.com/34786977/65130815-0bb07d80-d9b3-11e9-816b-22c7510658c1.png)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Compile the latest source code on Ubuntu 16.04
2. Waiting for results and look at the console...

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

91d6237

##### OPERATING SYSTEM:

Ubuntu 16.04

##### MODULES:

mod-weapon-visual
mod-transmog

##### OTHER CUSTOMIZATIONS:

none

**Comment by Viste** [comment]
please show you clang and gcc/g++ versions

**Comment by FrancescoBorzi** [comment]
make sure your `clang` version is at least 6+

**Comment by ide1234000** [comment]
> make sure your `clang` version is 6 or higher

Is the recent source upgrade? I used to be able to compile with clang 3.8

**Comment by ide1234000** [comment]
> please show you clang and gcc/g++ versions

clang 3.8 / g++ (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609

**Comment by Viste** [comment]
yes we updated to use C++17 standards and need to update clan for it to 6 and higher

**Comment by ide1234000** [comment]
Got it. Thank you all!
